FROM python:3.10-slim
WORKDIR /programas/my_project
RUN pip install fastapi pydantic mysql-connector-python passlib python-jose uvicorn
COPY . .
EXPOSE 8080
CMD ["uvicorn", "app_medicos:app", "--host", "0.0.0.0", "--port", "8080"]
